using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace AgriCheck.Infrastructure.Services;

public static class CertificatePdfGenerator
{
    static CertificatePdfGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] Generate(string title, string certificateNumber, string holderName, string verificationCode, string verifyUrl, string? qrBase64)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header().Column(col =>
                {
                    col.Item().Text("AgriCheck Certificate").FontSize(24).Bold().FontColor(Colors.Green.Darken2);
                    col.Item().Text(title).FontSize(16);
                });

                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().Text($"Certificate No: {certificateNumber}").Bold();
                    col.Item().Text($"Issued to: {holderName}");
                    col.Item().Text($"Verification Code: {verificationCode}");
                    col.Item().PaddingTop(10).Text($"Verify at: {verifyUrl}").FontSize(10).FontColor(Colors.Grey.Darken1);

                    if (!string.IsNullOrWhiteSpace(qrBase64) && qrBase64.StartsWith("data:image/png;base64,", StringComparison.OrdinalIgnoreCase))
                    {
                        var raw = qrBase64["data:image/png;base64,".Length..];
                        var bytes = Convert.FromBase64String(raw);
                        col.Item().PaddingTop(20).Width(120).Height(120).Image(bytes);
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by AgriCheck V3 · ");
                    text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm UTC")).FontSize(9);
                });
            });
        }).GeneratePdf();
    }
}
