using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace AgriCheck.Infrastructure.Services;

public static class PaymentReceiptPdfGenerator
{
    static PaymentReceiptPdfGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] Generate(
        string billNumber,
        string description,
        decimal amount,
        string paymentMethod,
        string? externalReference,
        DateTime paidAt,
        string payerName,
        string? entryReferenceNo)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text("AgriCheck Payment Receipt").FontSize(22).Bold().FontColor(Colors.Green.Darken2);
                    col.Item().Text("Official payment confirmation").FontSize(12).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().Text($"Receipt for Bill: {billNumber}").Bold();
                    col.Item().PaddingTop(8).Text($"Paid by: {payerName}");
                    col.Item().Text($"Description: {description}");
                    if (!string.IsNullOrWhiteSpace(entryReferenceNo))
                    {
                        col.Item().Text($"Entry reference: {entryReferenceNo}");
                    }
                    col.Item().PaddingTop(12).Text($"Amount paid: PHP {amount:N2}").FontSize(14).Bold();
                    col.Item().Text($"Payment method: {paymentMethod}");
                    if (!string.IsNullOrWhiteSpace(externalReference))
                    {
                        col.Item().Text($"Reference: {externalReference}");
                    }
                    col.Item().Text($"Paid at: {paidAt:yyyy-MM-dd HH:mm} UTC");
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by AgriCheck V3 · ");
                    text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm UTC")).FontSize(9);
                });
            });
        }).GeneratePdf();
    }
}
